In [1]:
import pandas as pd

In [81]:
df=pd.read_csv('StudentsPerformance.csv')

In [82]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [83]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [84]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [85]:
df['avg_score']=(df['math score']+df['reading score']+df['writing score'])//3

In [86]:
df['avg_score']=df['avg_score'].astype(int)

In [87]:
df['target']=(df['avg_score'] >=40).astype(int)

In [88]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,avg_score,target
0,female,group B,bachelor's degree,standard,none,72,72,74,72,1
1,female,group C,some college,standard,completed,69,90,88,82,1
2,female,group B,master's degree,standard,none,90,95,93,92,1
3,male,group A,associate's degree,free/reduced,none,47,57,44,49,1
4,male,group C,some college,standard,none,76,78,75,76,1

In [90]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

In [91]:
df.corr()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,avg_score,target
gender,1.000000,-0.001502,0.001913,0.021372,-0.006028,0.167982,-0.244313,-0.301225,-0.130483,0.005397
race/ethnicity,-0.001502,1.000000,-0.031946,0.046563,-0.017508,0.216415,0.145253,0.165691,0.185131,0.041662
parental level of education,0.001913,-0.031946,1.000000,0.006320,-0.023968,-0.068279,-0.072444,-0.084299,-0.078188,-0.068668
lunch,0.021372,0.046563,0.006320,1.000000,0.017044,0.350877,0.229560,0.245769,0.290390,0.163546
test preparation course,-0.006028,-0.017508,-0.023968,0.017044,1.000000,-0.177702,-0.241780,-0.312946,-0.256737,-0.094642
math score,0.167982,0.216415,-0.068279,0.350877,-0.177702,1.000000,0.817580,0.802642,0.918771,0.410651
reading score,-0.244313,0.145253,-0.072444,0.229560,-0.241780,0.817580,1.000000,0.954598,0.970048,0.421823
writing score,-0.301225,0.165691,-0.084299,0.245769,-0.312946,0.802642,0.954598,1.000000,0.965409,0.416313
avg_score,-0.130483,0.185131,-0.078188,0.290390,-0.256737,0.918771,0.970048,0.965409,1.000000,0.437658
target,0.005397,0.041662,-0.068668,0.163546,-0.094642,0.410651,0.421823,0.416313,0.437658,1.000000

In [92]:
X=df.drop(['target','avg_score'],axis=1)

In [93]:
print(X)

     gender  race/ethnicity  parental level of education  lunch  \
0         0               1                            1      1
1         0               2                            4      1
2         0               1                            3      1
3         1               0                            0      0
4         1               2                            4      1
..      ...             ...                          ...    ...
995       0               4                            3      1
996       1               2                            2      0
997       0               2                            2      0
998       0               3                            4      1
999       0               3                            4      0

     test preparation course  math score  reading score  writing score
0                          1          72             72             74
1                          0          69             90             88
2                          1          90             95             93
3                          1          47             57             44
4                          1          76             78             75
..                       ...         ...            ...            ...
995                        0          88             99             95
996                        1          62             55             55
997                        0          59             71             65
998                        0          68             78             77
999                        1          77             86             86

[1000 rows x 8 columns]

In [94]:
y=df['target']

In [95]:
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
995    1
996    1
997    1
998    1
999    1
Name: target, Length: 1000, dtype: int64

In [97]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [100]:
from sklearn.linear_model import LogisticRegression

In [102]:
lr=LogisticRegression(max_iter=1000)

In [103]:
lr.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [104]:
y_pred=lr.predict(X_test)

In [105]:
from sklearn.metrics  import accuracy_score

In [106]:
print(accuracy_score(y_test,y_pred))

1.0